name: myenv
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - backports.functools_lru_cache
  - backports_abc
  - ca-certificates
  - certifi
  - cloudpickle
  - cycler
  - dask-core
  - expat
  - functools32
  - futures
  - h5py=2.8.0
  - hdf5
  - icu=58.2
  - imageio
  - kiwisolver
  - libxml2
  - linecache2
  - matplotlib
  - networkx
  - openssl
  - pcre
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - pywavelets
  - qt
  - scikit-image
  - scipy
  - singledispatch
  - sip
  - subprocess32
  - toolz
  - tornado
  - traceback2
  - unittest2
  - backports
  - backports.shutil_get_terminal_size
  - blas
  - cffi
  - cudatoolkit
  - decorator
  - enum34
  - freetype
  - intel-openmp
  - ipython
  - ipython_genutils
  - jpeg
  - libpng
  - libtiff
  - mkl
  - mkl_fft
  - mkl_random
  - ninja
  - numpy
  - numpy-base
  - olefile
  - pathlib2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt_toolkit
  - pycparser
  - pygments
  - python=2.7.15
  - readline
  - scandir
  - setuptools
  - simplegeneric
  - six
  - sqlite
  - tk
  - traitlets
  - wcwidth
  - wheel
  - xz
  - zlib
  - pytorch
  - torchvision==0.2.1
  - pip:
    - dask==0.18.1
    - nltk==3.3
    - scikit-learn==0.19.2
    - sklearn==0.0
    - torch==0.4.0