apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-train-sgae
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi